### ISSUE TITLE
SSL Error when attempting to download SSL torckers

### ISSUE THREAD

**Issue by wseedbox** [autodl-community/autodl-irssi#168] opened 2018-11-18 13:50 UTC
I recently upgraded from Fedora 28 to Fedora 29.  In Fedora 28, everything worked as expected, in Fedora 29, I'm getting issues downloading SSL torrent links (https).

In the irssi output, I see a lot of these errors:

```
Irssi:  ERROR:  Error downloading torrent file 
https://www.ipXXXX.com/download.php/3095426/XXXX7b0ff3ae77a34. Error: _onReadAvailable ex: Could not read: SSL: Unknown error code: 5
```

I also see the some that are downloaded just fine from trackers that aren't using SSL.

I am not using CPAN.  I am using the perl packages provided with distro via DNF.   Here are the packages installed that the Requirements list.  Of course I have other perl packages, these are just what are listed from the install requirements.

perl-Archive-Zip-1.64-1.fc29.noarch
perl-Net-SSLeay-1.85-8.fc29.x86_64
perl-HTML-Entities-Interpolate-1.10-7.fc29.noarch
perl-HTML-Entities-Numbered-0.04-25.fc29.noarch
perl-XML-LibXML-2.0132-4.fc29.x86_64
perl-Digest-SHA-6.02-4.fc29.x86_64
perl-JSON-XS-3.04-5.fc29.x86_64
perl-JSON-2.97.001-4.fc29.noarch

I am happy to troubleshoot, just not sure how to debug Perl.

**Comment by wseedbox** [comment] 2018-12-31 14:15
Why was this closed? Is there anything I can do to troubleshoot this?

**Comment by travikk** [comment] 2019-01-03 10:37
I'm having the same issue. @thebigmunch any help?

**Comment by cainerwolf** [comment] 2019-01-21 01:38
I am also seeing this error with a brand new installation.  Not sure if it's SSL protocol, SSL certificate, etc.  I'm able to grab the file directly using the exact same URL with wget on the CLI.  No idea why I'm seeing this error.

17:25 -!- Irssi:  ERROR:  Error downloading torrent file 
https://www.i########.com/download.php/########.torrent?torrent_pass=########. Error: _onReadAvailable ex: Could not read: SSL: Unknown error code: 5

**Comment by torrent329** [comment] 2019-02-16 17:42
i'm getting this also with a fresh install- any ideas?

**Comment by IceBear2k** [comment] 2019-02-16 21:54
I've also encountered this error. All I know at the moment is that it seems to be related to a recent package as it only happens on the latest OS versions:

* Fedora 28 works, 29 doesn't
* Alpine 3.8 works, 3.9 doesn't
* Debian 9 works, 10/testing doesn't

I didn't track the causing package down, maybe this info helps.

**Comment by torrent329** [comment] 2019-02-16 22:55
my workaround was installing Ubuntu 16.04.5 and it worked perfectly- something about 18.10 gives that error

**Comment by wseedbox** [comment] 2019-02-22 22:45
@thebigmunch can we re-open this to get some eyes on it?  Seems to be happening now to newer linux distros.

**Comment by MrSIfter** [comment] 2019-03-22 12:32
I'm also have this issue on a fresh install of Ubuntu 18.10, is there a fix for this yet?

**Comment by reyder** [comment] 2019-04-19 08:09
I think here is the issue: [https://sources.debian.org/src/libnet-ssleay-perl/1.85-2/debian/patches/Adapt-to-OpenSSL-1.1.1.patch/](url)

I have just applied patch. Currently testing.

**Comment by wseedbox** [comment] 2019-04-19 18:41
@reyder Did you get it to work?  Can you let me know if it does work, what did you do?  Thanks!

**Comment by horjulf** [comment] 2019-04-20 05:13
Alpine 3.9 includes this patch, doesn't fix this issue.
https://build.alpinelinux.org/buildlogs/build-3-9-x86_64/main/perl-net-ssleay/perl-net-ssleay-1.85-r4.log

**Comment by reyder** [comment] 2019-04-20 07:51
It works:

`17:26 -!- Irssi: Matched *** in Episode (BTN Shows), BTN
17:26 -!- Irssi: Sent torrent to rtorrent ***, BTN, total time 1.033 seconds`

**Comment by notojak** [comment] 2019-05-13 17:02
@reyder,  ...on what distribution? But, for debian 10 doesn't work this

**Comment by reyder** [comment] 2019-05-13 17:05
It works. I tested this patch on Debian.

**Comment by lisim** [comment] 2019-05-22 22:02
I'm on Debian and also getting this error the packaged version of ssleay is 1.8.0 and cpan is 1.8.8 not sure what to do

**Comment by mnechita** [comment] 2019-05-23 19:13
Same issue on Cygwin, tried downgrading openssl and libopenssl 1.1.1 to 1.0.2 but problem persists. Also tried the latest SSLeay 1.88 and it still doesn't work.

**Comment by mnechita** [comment] 2019-05-24 06:57
@reyder Can you give a list of the versions that worked for you (openssl, libssl, Net::SSLeay, and all the other packages) ?

**Comment by reyder** [comment] 2019-05-24 07:47
Just look here: [https://github.com/radiator-software/p5-net-ssleay/commit/d91d869f0de5319704a3119c1e2f69d98818eaa2](url)

Read the patch and you will know why it does not work. It's one liner to fix (autodl-irssi
).

**Comment by mnechita** [comment] 2019-05-24 08:49
@reyder  thanks.

Soo, changing 
`my $got = Net::SSLeay::read($self->{ssl}, $len);`
to
`my $got = Net::SSLeay::ssl_read_all($self->{ssl}, $len);`
in sub **__doRead_** from _**SslSocket.pm**_ seems to have fixed the problem.

If this is the true fix, can someone with Perl experience issue a PR?

**Comment by impressioncr** [comment] 2019-08-14 02:29
@mnechita 
Thank you . Fixed it.

**Comment by DJPolyBi** [comment] 2019-08-20 14:42
I have followed all of the guides I have found online so far.

I keep getting this error code:
`Could not read: SSL: Unknown error code: 5`

- I am on a Seedbox running Debian 8.11
- I have tried using Force SSL
- I have tried: 
```bash
cd
cd .irssi
cd scripts/AutodlIrssi
wget https://raw.github.com/mnechita/autodl-irssi/master/AutodlIrssi/SslSocket.pm -O SslSocket.pm
```

None of these fixes have unfortunately solved my issue.  Any help would be appreciated.  Thank you!

**Comment by DJPolyBi** [comment] 2019-08-21 16:02
I just checked my PERL module versions they are current as well:

https://imgur.com/a/9Y170td

**Comment by tasoss** [comment] 2019-08-26 18:42
Hello. @impressioncr  have you commited the fix?

**Comment by root-host** [comment] 2019-09-02 18:52
this the fix don't work,now im getting HTTP1.1 800 Internal Server Error

**Comment by koblack** [comment] 2019-09-08 08:44
I'm also having the same issue.

**Comment by LeCommonMan** [comment] 2019-09-08 12:07
> Error: _onReadAvailable ex: Could not read: SSL: Unknown error code: 5

do we have any solution for this error yet?

**Comment by LeCommonMan** [comment] 2019-09-08 12:36
> @mnechita
> Thank you . Fixed it.

@impressioncr any suggestion how you fixed it? 
i am unable to located the file **SslSocket.pm** in the install directory.

**Comment by LeCommonMan** [comment] 2019-09-08 13:37
> I'm also having the same issue.

check this out, might be helpful - https://old.reddit.com/r/seedboxes/comments/c9cdir/autodlirss_command_error/eszubn9/

**Comment by root-host** [comment] 2019-09-13 15:44
Unticking SSL also dont work,the fix you posted also don't work,after restarting autodl-irssi there is error http internal error.

**Comment by root-host** [comment] 2019-09-13 15:47
> I'm also having the same issue.

everone who uses 2.5.0 have the same issue, seems that author of this pugin not going to fix this soon.

**Comment by thebigmunch** [comment] 2019-09-13 16:15
> everone who uses 2.5.0 have the same issue, seems that author of this pugin not going to fix this soon.

Don't be an entitled douchebag. That's not how open source works. And it's people like you who made me pull most of my effort away from this particular project in the first place. You won't be welcome here anymore.

Also, far from everyone is having this issue. And the problem is that people have come up with a solution for the relatively small number of people that have already run into the issue of having a newer version of Net::SSLeay on their system that requires using a new read method without making it backward-compatible for the much larger number of people who don't.

**Comment by fsamareanu** [comment] 2019-09-14 16:12
@thebigmunch to be fair the number is only going to increase as Debian 10/Ubuntu 18 gets traction. And I don't think @root-host is entitled but based on his speech pattern english isn't his first language.
Anyway the fix for I tested the fix on 2 Debian 10 installs and it works for me (TM).

**Comment by thebigmunch** [comment] 2019-09-14 18:03
> @thebigmunch to be fair the number is only going to increase as Debian 10/Ubuntu 18 gets traction.

To be fair, most people would assume I know that even if they didn't read my comment. So ask yourself why you felt the need to say that.

> And I don't think @root-host is entitled but based on his speech pattern english isn't his first language.

So, your response to what you saw me say that you don't actually know if there's more to is to make another assumption. FIrst language or not (I've seen native speakers with similar or worse speech patterns), they made an unnecessary post within minutes of their previous post to say something that was clearly false to anyone who isn't letting emotion get in the way of basic logical thinking and then said something that clearly denotes entitlement. I'm easy to get in touch with, so if I were wrong they could explain or just tell me off. With what I know, I'd put good money on me being right. What about you?

> Anyway the fix for I tested the fix on 2 Debian 10 installs and it works for me (TM).

Indeed. And when I need it, I will apply a backward-compatible patch. Until then, this is an object lesson in both open source development and community (or the lack thereof) in the world of P2P these days.

For the record, I didn't even start using autodl until at least 6 months after I started working on it over 7 years ago. Is not one person that's running into this issue willing to try to make the fix backward-compatible? Multiple people have come to the solution for the new library version, but nobody seems to care about the rest of the autodl users (i.e. the community).

**Comment by fsamareanu** [comment] 2019-09-14 18:33
Yes. I'm willing to bet that his first language isn't English. Read the rutorrent issue above and you'll see what I mean. Other than that, we are battling assumptions. And yes, if you're willing to make a wager with me I'm more than open to it.

> Indeed. And when I need it, I will apply a backward-compatible patch. Until then, this is an object lesson in both open source development and community (or the lack thereof) in the world of P2P these days.

I don't know about that, rutorrent/rtorrent seem to have active contributors.

> For the record, I didn't even start using autodl until at least 6 months after I started working on it over 7 years ago. Is not one person that's running into this issue willing to try to make the fix backward-compatible? Multiple people have come to the solution for the new library version, but nobody seems to care about the rest of the autodl users (i.e. the community).

That's mostly up to you. For example pfsense project doesn't close a pull request without giving the requester a change to review their code and do the necessary fixes (see #179 vs https://github.com/pfsense/pfsense/pull/4077 ).

**Comment by chrisawad** [comment] 2019-09-24 04:00
Thanks @reyder and @mnechita, that fix with ssl_read_all worked for me too.

**Comment by lepercahun** [comment] 2019-10-15 00:54
Thanks @reyder and @mnechita, that fix with ssl_read_all worked for me too. 👍

**Closed** 2019-10-28 19:35 UTC

**Comment by khnielsen** [comment] 2019-10-29 18:03
@thebigmunch - Just a note, this is still broken on Debian 10, default version for that is 1.85 - I see you noted 1.86 as the minimum required to trigger the workaround, might be worth bumping that down a notch to 1.85 ;)

**Comment by SavageCore** [comment] 2019-10-29 18:10
> @thebigmunch - Just a note, this is still broken on Debian 10, default version for that is 1.85 - I see you noted 1.86 as the minimum required to trigger the workaround, might be worth bumping that down a notch to 1.85. Atleast, for me, forcing it onto the newer way of handling ssl_read makes it run smooth, so I assume it would work, I can run a quick pre-test to make sure if you would like.

It'll work either way, the code just checks for the existence of the new function, not tied to versions :)

**Comment by SavageCore** [comment] 2019-10-29 18:34
> @thebigmunch - Just a note, this is still broken on Debian 10, default version for that is 1.85 - I see you noted 1.86 as the minimum required to trigger the workaround, might be worth bumping that down a notch to 1.85. Atleast, for me, forcing it onto the newer way of handling ssl_read makes it run smooth, so I assume it would work, I can run a quick pre-test to make sure if you would like.

Confirmed, the initial fix checking if it exists worked fine on Debian 10 so either back to that or check against 1.85

**Comment by khnielsen** [comment] 2019-10-29 18:36
@SavageCore - I have had this happen on 9 debian 10 installs so far, all fully updated where the check didnt fix before I forced it onto the "patch" above, I have not tried setting the check against 1.85 yet but I will do that.

**Comment by AlcDenat** [comment] 2019-10-29 19:05
Confirming, latest update ( https://github.com/autodl-community/autodl-irssi/commit/04eda267dcc601f4bf5d3a8a85aada8c17ccb61a ) broke it again for me on Debian 10.

Fixed it again by hand for me.

**Comment by SavageCore** [comment] 2019-10-29 19:12
Both were broken actually, my bad! exists and version check against 1.86, testing 1.85...

**Comment by snooptodd** [comment] 2019-10-29 23:20
`$Net::SSLeay::VERSION >= 1.85` works for me also on Ubuntu 18.04.3

**Comment by fsamareanu** [comment] 2019-10-30 05:43
Ubuntu 18.04 LTS uses libnet-ssleay-perl version 1.84-1ubuntu0.2 which is also affected by the update. Testing changing the parameter to >=1.8.4 , waiting for next torrent match.

**Comment by fsamareanu** [comment] 2019-10-30 18:46
Did you restart irssi after?

**Comment by Mitnick84** [comment] 2019-10-30 19:49
yes

**Comment by jsdukeboy08** [comment] 2019-10-30 20:38
changing to $Net::SSLeay::VERSION >= 1.84 in ubuntu 18.04.3 LTS worked for me after restarting irssi

**Comment by Mitnick84** [comment] 2019-10-31 08:32
Okay, i changed it also to $Net::SSLeay::VERSION >= 1.84
My SSL version is OpenSSL 1.1.1d  10 Sep 2019
rebooted the server and its not working!

**Comment by Mitnick84** [comment] 2019-10-31 11:12
(1:519)# dpkg -l|grep ssleay
ii  libcrypt-ssleay-perl                                        0.73.04-2build2                                             amd64        OpenSSL support for LWP
ii  libnet-ssleay-perl                                          1.84-1ubuntu0.2                                             amd64        Perl module for Secure Sockets Layer (SSL)

**Comment by johnpowell** [comment] 2019-10-31 11:42
$Net::SSLeay::VERSION >= 1.84 also worked for me on 18.04.3.

**Comment by Mitnick84** [comment] 2019-10-31 11:55
i removed irssi and reinstalled complete new and changed to $Net::SSLeay::VERSION >= 1.84, it works now

**Comment by trackerone** [comment] 2019-11-02 12:22
Could we get this issue open again? 
Also got error code 5 again

**Comment by fsamareanu** [comment] 2019-11-02 13:17
There was no recent update to autodl (last one was 5 days ago). Read the last 10 posts of this issue and see if the version fix works for you.

**Comment by chrisawad** [comment] 2019-11-03 22:38
> i tried $Net::SSLeay::VERSION >= 1.85 and 1.84 and 1.86 its not working in ubuntu 18.04 LTS

I had the same problem. The update broke my manual fix. Saw that the update just wrapped it in an if, so I took out the if again and all was fine.

Looks like the version number just needs to be refined a little.

**Comment by blixten85** [comment] 2019-11-04 03:24
> > i tried $Net::SSLeay::VERSION >= 1.85 and 1.84 and 1.86 its not working in ubuntu 18.04 LTS
> 
> I had the same problem. The update broke my manual fix. Saw that the update just wrapped it in an if, so I took out the if again and all was fine.
> 
> Looks like the version number just needs to be refined a little.

What if?
Please paste what you have changed, full lines of it.

And i have the same issue as reported above, running the latest version of both debian 10 x64 and autodl-irssi.

**Comment by MiningInMySleep** [comment] 2019-11-06 11:14
Running Debian 10 and also getting this error.

**Comment by khnielsen** [comment] 2019-11-06 11:20
Unless your OS is outdated or have incorrect dependencies then changing;

$Net::SSLeay::VERSION >= 1.86 to $Net::SSLeay::VERSION >= 1.84 in the SslSocket.pm file will resolve the problem here, 1.85 is required for Debian 10, and ubuntu 1804 needs it dropped to 1.84

Make sure to restart autodl entirely after editing it, if it is still not working then you need to post diags on what dependencies you have installed, by doing this; 

dpkg -l|grep ssleay

And then posting the output - The fix is easy and works.

**Comment by blixten85** [comment] 2019-11-06 11:36
ah yeah i managed to sort it, i made that change down to 1.84 on debian 10, x64. 

dpkg -l|grep ssleay
ii  libnet-ssleay-perl            1.85-2+b1                    amd64        Perl module for Secure Sockets Layer (SSL)

system is fully updated.
